services:
  db:
    image: mysql:8.0
    container_name: nitromedicas-db
    environment:
      MYSQL_DATABASE: nitromedicas_db
      MYSQL_USER: nitro_user
      MYSQL_PASSWORD: nitro_pass
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 20s

  backend:
    container_name: nitromedicas-backend
    build:
      context: ./nitromedicas-back
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/nitromedicas_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: nitro_user
      SPRING_DATASOURCE_PASSWORD: nitro_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: nitromedicas-frontend
    build:
      context: ./nitromedicas-app
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mysql_data:
